### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ASTPlatinum** [springfall2008/predbat_addon#5]
I cannot install this addon. The following error is reported.

The command '/bin/bash -o pipefail -c apt-get install -y python3' returned a non-zero code: 100

HA Logs: Failed to to call /addons/6adb4f0d_predbat/install - The command '/bin/bash -o pipefail -c apt-get install -y python3' returned a non-zero code: 100

Can install other addons with no problems.

Supervisor logs

2024-06-15 16:53:39.183 INFO (MainThread) [supervisor.docker.addon] Starting build for 6adb4f0d/amd64-addon-predbat:1.1.7
2024-06-15 16:53:40.208 ERROR (MainThread) [supervisor.docker.addon] Can't build 6adb4f0d/amd64-addon-predbat:1.1.7: The command '/bin/bash -o pipefail -c apt-get install -y python3' returned a non-zero code: 100
2024-06-15 16:53:40.209 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/29 : ARG BUILD_FROM
Step 2/29 : ARG BUILD_VERSION
Step 3/29 : FROM $BUILD_FROM
 ---> 878dda02f55b
Step 4/29 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> ce8439c7ad23
Step 5/29 : RUN apt-get update
 ---> Using cache
 ---> b358006050a4
Step 6/29 : RUN apt-get upgrade -y
 ---> Using cache
 ---> dadffd6069b5
Step 7/29 : RUN apt-get dist-upgrade -y
 ---> Using cache
 ---> 823f21dd5b56
Step 8/29 : RUN apt-get install -y python3
 ---> Running in e604a552cbdc
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3
 ---> Removed intermediate container e604a552cbdc

Any ideas? :(

**Comment by springfall2008** [comment]
I don't understand why Python3 isn't found, what system do you have?

**Comment by ASTPlatinum** [comment]
> I don't understand why Python3 isn't found, what system do you have?

Running on docker.

If I jump into the container console of the supervisor you can see what version of Python is installed!

![Screenshot 2024-06-16 192830](https://github.com/springfall2008/predbat_addon/assets/59362338/26ed1cae-bdbf-409e-abc7-746b2e2d9edd)

**Comment by ASTPlatinum** [comment]
@springfall2008 Just forked, changed the following in dockerfile

RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y

To

RUN apt-get update && apt-get install -y

And the install ran fine.

**Comment by springfall2008** [comment]
I've made the suggested change in 1.1.8 but I don't understand why it would help
