### ISSUE TITLE
App terminates itself after applying an update

### ISSUE THREAD

**Issue by github-dpmracing** [springfall2008/predbat_addon#8]
Core 2024.6.3
HASS Operating System 12.4
Running predbat on a Standalone HA instance reporting back into a main HA instance
predbat 8.1.0/8.1.1

For the last few updates to predbat my predbat instance has identified the new install, updated, installed it and carried out a single pass and then quietly stopped running.

The Add-on App log shows normal operation, then the install, the single pass result and then just "states stopping due to file changes"

> 2024-06-23 12:25:10.488392: Info: record_status Freeze discharging target 36%-40%
> 2024-06-23 12:31:54.829108: Info: record_status Idle
> 2024-06-23 12:35:10.259403: Info: record_status Idle
> 2024-06-23 12:41:01.374787: Info: record_status Idle
> 2024-06-23 12:45:10.366463: Info: record_status Idle
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/predbat.py
> Got data, writing to /config/predbat.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/config.py
> Got data, writing to /config/config.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/prediction.py
> Got data, writing to /config/prediction.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/utils.py
> Got data, writing to /config/utils.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/inverter.py
> Got data, writing to /config/inverter.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/ha.py
> Got data, writing to /config/ha.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/download.py
> Got data, writing to /config/download.py.v8.1.1
> Downloading https://raw.githubusercontent.com/springfall2008/batpred/v8.1.1/apps/predbat/unit_test.py
> Got data, writing to /config/unit_test.py.v8.1.1
> Update complete
> 2024-06-23 12:51:26.876780: Info: record_status Freeze discharging target 39%-43%
> File ./config.py was modified
> Stopping Predbat due to file changes....
> 2024-06-23 12:51:26.899087: Stopping Predbat

The full predbat.log doesn't show anything particularly "error" like.....

> 2024-06-23 12:45:10.329638: Completed run status Idle
> 2024-06-23 12:45:10.366463: Info: record_status Idle
> 2024-06-23 12:45:10.394813: Saved current settings to /config/predbat_config.json

Last run completes and the next action is at 12:50 when the run detects the new firmware and installs and then runs...

> 2024-06-23 12:50:00.872025: --------------- PredBat - update at 2024-06-23 12:50:00+01:00 with clock skew 0 minutes, minutes now 770
> 2024-06-23 12:50:00.872331: Saved current settings to /config/predbat_config.json
> 2024-06-23 12:50:01.023713: Predbat /config/predbat.py version v8.1.0 currently running, latest version is v8.1.1 latest beta v8.1.1
> 2024-06-23 12:50:01.023779: Autoupdate: There is an update pending v8.1.1 Bug fixes for clipping & pause mode, unit testing - auto update triggered!
> 2024-06-23 12:50:01.023793: Update Predbat to version v8.1.1 Bug fixes for clipping & pause mode, unit testing
> 2024-06-23 12:50:02.185072: Kill current threads before update
> 2024-06-23 12:50:02.940372: Perform the update.....
> 2024-06-23 12:50:02.949663: Update to version v8.1.1 Bug fixes for clipping & pause mode, unit testing completed
> 2024-06-23 12:50:03.008710: Configuration: forecast_hours 48 num_cars 1 debug enable is False calculate_plan_every 10
> 2024-06-23 12:50:03.008891: Cars 1 charging from battery False planned [False], charging_now [False] smart [False], max_price [0.0], plan_time ['07:00:00'], battery size [100.0], limit [100.0], rate [7.4]
> 2024-06-23 12:50:03.008919: Predbat mode is set to Control charge & discharge
> 2024-06-23 12:50:03.874740: Found 11521 load_today datapoints going back 8 days
> 2024-06-23 12:50:05.597469: Current data so far today: load 8.7 kWh import 7.2 kWh export 0.1 kWh pv 7.1 kWh
> 2024-06-23 12:50:05.597548: Fetching futurerate data from None
> 2024-06-23 12:50:05.601958: Fetching carbon intensity data from sensor.carbon_intensity_uk
 
SNIPPED Lots of this normal run log 
 
> 2024-06-23 12:51:26.006820: Discharge Freeze as discharge is now at/below target - current SOC 5.29 and target 5.8351
> 2024-06-23 12:51:26.006867: Not setting charging SOC as we are not within the window (now 06-23 12:50:00 target set_soc_minutes 30 charge start time 06-23 13:30:00)
> 2024-06-23 12:51:26.006877: Adjust reserve to default (as set_reserve_enable is true)
> 2024-06-23 12:51:26.006890: Inverter 0 Current reserve is 4.0 already at target
> 2024-06-23 12:51:26.157685: Completed run status Freeze discharging
> 2024-06-23 12:51:26.876780: Info: record_status Freeze discharging target 39%-43%
> 2024-06-23 12:51:26.898987: Saved current settings to /config/predbat_config.json
> 2024-06-23 12:51:26.899087: Stopping Predbat
> 2024-06-23 12:51:26.899113: Predbat terminating
> 2024-06-23 12:51:26.899223: Predbat terminated

This is the next log after I've restarted the app

> 2024-06-23 21:05:11.295530: Loading apps.yaml
> 2024-06-23 21:05:11.322012: Predbat: Startup predbat
> 2024-06-23 21:05:11.338111: --------------- PredBat - update at 2024-06-23 21:05:00+01:00 with clock skew 0 minutes, minutes now 1265
> 2024-06-23 21:05:11.338218: Config root is /config
> 2024-06-23 21:05:11.354050: Info: Connected to Home Assistant at http://XXXXXXX.220:8123
> 2024-06-23 21:05:11.354114: Creating task: <coroutine object HAInterface.socketLoop at 0x7f36e1bc3c30>
> 2024-06-23 21:05:11.354510: Info: Start socket for url http://XXXXXXXXXXXX.220:8123/api/websocket
> 2024-06-23 21:05:11.354554: Info: Web Socket task started
> 2024-06-23 21:05:11.355187: Sanity check:
> 2024-06-23 21:05:11.355377: Sanity scan files in '/config' : ['config.py', 'predbat_dashboard.yaml', 'ha.py', 'unzip', 'download.py', 'unit_test.py', 'inverter.py', 'predbat.log', 'predbat_v7.20.4.zip', 'apps-dist.yaml', 'predbat.py', 'prediction.py', 'utils.py', 'predbat_config.json', 'predbat_save', 'apps.yaml', 'hass.py', 'predbat.log.1', 'cache']
> 2024-06-23 21:05:11.355493: Warn: unable to find /config/appdaemon.yaml skipping checks as maybe outside AppDaemon
> 2024-06-23 21:05:11.381343: Info: Web Socket active
> 2024-06-23 21:05:11.445025: Regular expression argument geserial matched ^sensor.givtcp_(.+)_soc_kwh$ with ch2335g184

**Comment by springfall2008** [comment]
Terminated is normal, but it should restart in 30 seconds?
